# Generated by Django 4.1.3 on 2023-01-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='book',
            new_name='book_name',
        ),
    ]
