# Generated by Django 4.1.3 on 2023-01-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_reserve_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
